version: '3'

services:
  app:
    build: .
    entrypoint: ['tail', '-f', '/dev/null']
    volumes:
      - ./bin:/home/app/bin
      - ./charts:/home/app/charts
      - ./repo:/home/app/repo
    container_name: k8s-dep
